name: CI

on:
  push:
    branches:
      - main

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        run: make lint 

  tests-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3   

      - name: Tests
        run: make test
